#!/bin/bash


/opt/spark/bin/spark-submit --master local[1] --conf "spark.driver.maxResultSize=110g" --driver-memory 110g --class de.fraunhofer.iais.kd.haiqing.test SparkWord2Vec.jar /home/IAIS/hwang/SparkWord2Vec/MainSWSCSim1.txt /home/IAIS/hwang/SparkWord2Vec/simSWSC.txt > MainSWSCSim1.log

/opt/spark/bin/spark-submit --master local[1] --conf "spark.driver.maxResultSize=110g" --driver-memory 110g --class de.fraunhofer.iais.kd.haiqing.test SparkWord2Vec.jar /home/IAIS/hwang/SparkWord2Vec/MainSWSCSim2.txt /home/IAIS/hwang/SparkWord2Vec/simSWSC.txt > MainSWSCSim2.log

/opt/spark/bin/spark-submit --master local[1] --conf "spark.driver.maxResultSize=110g" --driver-memory 110g --class de.fraunhofer.iais.kd.haiqing.test SparkWord2Vec.jar /home/IAIS/hwang/SparkWord2Vec/MainSWSCSim3.txt /home/IAIS/hwang/SparkWord2Vec/simSWSC.txt > MainSWSCSim3.log

/opt/spark/bin/spark-submit --master local[1] --conf "spark.driver.maxResultSize=110g" --driver-memory 110g --class de.fraunhofer.iais.kd.haiqing.test SparkWord2Vec.jar /home/IAIS/hwang/SparkWord2Vec/MainSWSCSim4.txt /home/IAIS/hwang/SparkWord2Vec/simSWSC.txt > MainSWSCSim4.log

/opt/spark/bin/spark-submit --master local[1] --conf "spark.driver.maxResultSize=110g" --driver-memory 110g --class de.fraunhofer.iais.kd.haiqing.test SparkWord2Vec.jar /home/IAIS/hwang/SparkWord2Vec/MainSWSCSim5.txt /home/IAIS/hwang/SparkWord2Vec/simSWSC.txt > MainSWSCSim5.log

/opt/spark/bin/spark-submit --master local[1] --conf "spark.driver.maxResultSize=110g" --driver-memory 110g --class de.fraunhofer.iais.kd.haiqing.test SparkWord2Vec.jar /home/IAIS/hwang/SparkWord2Vec/MainSWSCSim6.txt /home/IAIS/hwang/SparkWord2Vec/simSWSC.txt > MainSWSCSim6.log

/opt/spark/bin/spark-submit --master local[1] --conf "spark.driver.maxResultSize=110g" --driver-memory 110g --class de.fraunhofer.iais.kd.haiqing.test SparkWord2Vec.jar /home/IAIS/hwang/SparkWord2Vec/MainSWSCSim7.txt /home/IAIS/hwang/SparkWord2Vec/simSWSC.txt > MainSWSCSim7.log

/opt/spark/bin/spark-submit --master local[1] --conf "spark.driver.maxResultSize=110g" --driver-memory 110g --class de.fraunhofer.iais.kd.haiqing.test SparkWord2Vec.jar /home/IAIS/hwang/SparkWord2Vec/MainSWSCSim8.txt /home/IAIS/hwang/SparkWord2Vec/simSWSC.txt > MainSWSCSim8.log

/opt/spark/bin/spark-submit --master local[1] --conf "spark.driver.maxResultSize=110g" --driver-memory 110g --class de.fraunhofer.iais.kd.haiqing.test SparkWord2Vec.jar /home/IAIS/hwang/SparkWord2Vec/maxSim1.txt /home/IAIS/hwang/SparkWord2Vec/sim.txt > maxSim1.log

/opt/spark/bin/spark-submit --master local[1] --conf "spark.driver.maxResultSize=110g" --driver-memory 110g --class de.fraunhofer.iais.kd.haiqing.test SparkWord2Vec.jar /home/IAIS/hwang/SparkWord2Vec/maxSim2.txt /home/IAIS/hwang/SparkWord2Vec/sim.txt > maxSim2.log

/opt/spark/bin/spark-submit --master local[1] --conf "spark.driver.maxResultSize=110g" --driver-memory 110g --class de.fraunhofer.iais.kd.haiqing.test SparkWord2Vec.jar /home/IAIS/hwang/SparkWord2Vec/maxSim3.txt /home/IAIS/hwang/SparkWord2Vec/sim.txt > maxSim3.log

/opt/spark/bin/spark-submit --master local[1] --conf "spark.driver.maxResultSize=110g" --driver-memory 110g --class de.fraunhofer.iais.kd.haiqing.test SparkWord2Vec.jar /home/IAIS/hwang/SparkWord2Vec/maxSim4.txt /home/IAIS/hwang/SparkWord2Vec/sim.txt > maxSim4.log

/opt/spark/bin/spark-submit --master local[1] --conf "spark.driver.maxResultSize=110g" --driver-memory 110g --class de.fraunhofer.iais.kd.haiqing.test SparkWord2Vec.jar /home/IAIS/hwang/SparkWord2Vec/maxSim5.txt /home/IAIS/hwang/SparkWord2Vec/sim.txt > maxSim5.log

/opt/spark/bin/spark-submit --master local[1] --conf "spark.driver.maxResultSize=110g" --driver-memory 110g --class de.fraunhofer.iais.kd.haiqing.test SparkWord2Vec.jar /home/IAIS/hwang/SparkWord2Vec/maxSim6.txt /home/IAIS/hwang/SparkWord2Vec/sim.txt > maxSim6.log

/opt/spark/bin/spark-submit --master local[1] --conf "spark.driver.maxResultSize=110g" --driver-memory 110g --class de.fraunhofer.iais.kd.haiqing.test SparkWord2Vec.jar /home/IAIS/hwang/SparkWord2Vec/maxSim7.txt /home/IAIS/hwang/SparkWord2Vec/sim.txt > maxSim7.log

/opt/spark/bin/spark-submit --master local[1] --conf "spark.driver.maxResultSize=110g" --driver-memory 110g --class de.fraunhofer.iais.kd.haiqing.test SparkWord2Vec.jar /home/IAIS/hwang/SparkWord2Vec/maxSim8.txt /home/IAIS/hwang/SparkWord2Vec/sim.txt > maxSim8.log

~                                                                                            
